notifications:
  email: false

language: generic

sudo: false

cache:
  directories:
    - $HOME/miniconda3

before_cache:
  - rm -rf $HOME/miniconda3/pkgs/cache
  - rm -rf $HOME/miniconda3/envs/hosts

os:
  - linux
  - osx

env:
  - PYTHON_VERSION="3.5"
  - PYTHON_VERSION="3.6"
  - PYTHON_VERSION="3.7"

before_install:
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - chmod +x ci/install_conda.sh
  - chmod +x ci/setup_conda_env.sh
  - chmod +x ci/test.sh
  - chmod +x ci/lint.sh

install:
  - ci/install_conda.sh
  - ci/setup_conda_env.sh

script:
  - ci/test.sh
  - ci/lint.sh
